name: Prise Build .net core 2

env:
  dotnetVersion: 2.1.802
  fwkVersion: 'netcoreapp2.1'

on: [push]

jobs:
  run-integration-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        
      - name: Setup .NET Core ${{dotnetVersion}}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{dotnetVersion}}
        
    - name: Build Prise with ${{fwkVersion}}
      run: dotnet build src/Prise/Prise.net2.csproj --configuration Release -f ${{fwkVersion}}

    - name: Build Prise.Mvc with ${{fwkVersion}}
      run: dotnet build src/Prise.Mvc/Prise.Mvc.net2.csproj --configuration Release -f ${{fwkVersion}}