name: Prise Build

on: [push]

env:
  dotnetVersion: 3.1.201
  fwkVersion: 'netcoreapp3.1'

on: [push]

jobs:
  run-integration-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        
      - name: Setup .NET Core ${{dotnetVersion}}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{dotnetVersion}}
        
    - name: Build Prise with netcoreapp2.1
      run: dotnet build src/Prise/Prise.csproj --configuration Release -f netcoreapp2.1
    - name: Build Prise with netcoreapp3.0
      run: dotnet build src/Prise/Prise.csproj --configuration Release -f netcoreapp3.0
    - name: Build Prise with netcoreapp3.1
      run: dotnet build src/Prise/Prise.csproj --configuration Release -f netcoreapp3.1

    - name: Build Prise.AssemblyScanning with netstandard2.0
      run: dotnet build src/Prise.AssemblyScanning/Prise.AssemblyScanning.csproj --configuration Release -f netstandard2.0

    - name: Build Prise.AssemblyScanning.Discovery with netstandard2.0
      run: dotnet build src/Prise.AssemblyScanning.Discovery/Prise.AssemblyScanning.Discovery.csproj --configuration Release -f netstandard2.0

    - name: Build Prise.AssemblyScanning.Discovery.Nuget with netstandard2.0
      run: dotnet build src/Prise.AssemblyScanning.Discovery.Nuget/Prise.AssemblyScanning.Discovery.Nuget.csproj --configuration Release -f netstandard2.0

    - name: Build Prise.Mvc with netcoreapp2.1
      run: dotnet build src/Prise.Mvc/Prise.Mvc.csproj --configuration Release -f netcoreapp2.1
    - name: Build Prise.Mvc with netcoreapp3.0
      run: dotnet build src/Prise.Mvc/Prise.Mvc.csproj --configuration Release -f netcoreapp3.0
    - name: Build Prise.Mvc with netcoreapp3.1
      run: dotnet build src/Prise.Mvc/Prise.Mvc.csproj --configuration Release -f netcoreapp3.1
        
    - name: Build Prise.Plugin with netstandard2.0
      run: dotnet build src/Prise.Plugin/Prise.Plugin.csproj --configuration Release -f netstandard2.0

    - name: Build Prise.PluginBridge with netstandard2.0
      run: dotnet build src/Prise.PluginBridge/Prise.PluginBridge.csproj --configuration Release -f netstandard2.0

    - name: Build Prise.Proxy with netstandard2.0
      run: dotnet build src/Prise.Proxy/Prise.Proxy.csproj --configuration Release -f netstandard2.0