name: Prise backwards compatibility .netcoreapp2.1

on: [push]

jobs:
  run-integration-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        
      - name: Setup .NET Core 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.802

      # Creates Prise beta versions
      - name: pack Prise
        run: dotnet pack -c Release /p:Version=1.9.0-beta1 -o ../../dist src/Prise/Prise.net2.csproj
      - name: pack Prise.Plugin
        run: dotnet pack -c Release /p:Version=1.9.0-beta1 -o ../../dist src/Prise.Plugin/Prise.Plugin.csproj
      - name: pack Prise.Proxy
        run: dotnet pack -c Release /p:Version=1.9.0-beta1 -o ../../dist src/Prise.Proxy/Prise.Proxy.csproj
      - name: pack Prise.PluginBridge
        run: dotnet pack -c Release /p:Version=1.9.0-beta1 -o ../../dist src/Prise.PluginBridge/Prise.PluginBridge.csproj
      - name: pack Prise.Mvc
        run: dotnet pack -c Release /p:Version=1.9.0-beta1 -o ../../dist src/Prise.Mvc/Prise.Mvc.net2.csproj
      - name: pack Prise.AssemblyScanning.Discovery
        run: dotnet pack -c Release /p:Version=1.9.0-beta1 -o ../../dist src/Prise.AssemblyScanning.Discovery/Prise.AssemblyScanning.Discovery.csproj
      - name: pack Prise.AssemblyScanning.Discovery.Nuget
        run: dotnet pack -c Release /p:Version=1.9.0-beta1 -o ../../dist src/Prise.AssemblyScanning.Discovery.Nuget/Prise.AssemblyScanning.Discovery.Nuget.csproj

      # Copies all published plugins to integration test directory
      - run: mkdir -p src/Tests/Prise.IntegrationTests/bin/Debug/netcoreapp2.1/Plugins
      - run: cp -r src/Tests/compatibility/netstandard2.0/PluginA src/Tests/Prise.IntegrationTests/bin/Debug/netcoreapp2.1/Plugins
      - run: cp -r src/Tests/compatibility/netstandard2.0/PluginB src/Tests/Prise.IntegrationTests/bin/Debug/netcoreapp2.1/Plugins
      - run: cp -r src/Tests/compatibility/netstandard2.0/PluginC src/Tests/Prise.IntegrationTests/bin/Debug/netcoreapp2.1/Plugins
      - run: cp -r src/Tests/compatibility/netcoreapp2.1/PluginD src/Tests/Prise.IntegrationTests/bin/Debug/netcoreapp2.1/Plugins
      - run: cp -r src/Tests/compatibility/netcoreapp2.1/PluginE src/Tests/Prise.IntegrationTests/bin/Debug/netcoreapp2.1/Plugins
      - run: cp -r src/Tests/compatibility/netcoreapp2.1/PluginF src/Tests/Prise.IntegrationTests/bin/Debug/netcoreapp2.1/Plugins
      - run: cp -r src/Tests/compatibility/netstandard2.0/LegacyPlugin1.4 src/Tests/Prise.IntegrationTests/bin/Debug/netcoreapp2.1/Plugins
      - run: cp -r src/Tests/compatibility/netstandard2.0/LegacyPlugin1.5 src/Tests/Prise.IntegrationTests/bin/Debug/netcoreapp2.1/Plugins

      - name: Restore IntegrationTestsHost.net2
        run: dotnet restore src/Tests/Prise.IntegrationTestsHost/Prise.IntegrationTestsHost.net2.csproj --configfile src/Tests/Prise.IntegrationTestsHost/NuGet.config

      - name: Test Prise.IntegrationTests with netcoreapp2.1
        run: dotnet test src/Tests/Prise.IntegrationTests/Prise.IntegrationTests.net2.csproj
