name: Prise backwards compatibility tests netcoreapp3.0 => net5.0

on: [push]

jobs:
  run-integration-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        
      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100-preview.4.20258.7

      # Copies all plugins to integration test directory
      - run: mkdir -p src/Tests/Prise.IntegrationTests/bin/Debug/net5.0/Plugins
      - run: cp -r src/Tests/compatibility/netstandard2.1/PluginA src/Tests/Prise.IntegrationTests/bin/Debug/net5.0/Plugins
      - run: cp -r src/Tests/compatibility/netstandard2.0/PluginB src/Tests/Prise.IntegrationTests/bin/Debug/net5.0/Plugins
      - run: cp -r src/Tests/compatibility/netstandard2.0/PluginC src/Tests/Prise.IntegrationTests/bin/Debug/net5.0/Plugins
      - run: cp -r src/Tests/compatibility/netcoreapp3.0/PluginD src/Tests/Prise.IntegrationTests/bin/Debug/net5.0/Plugins
      - run: cp -r src/Tests/compatibility/netcoreapp3.0/PluginE src/Tests/Prise.IntegrationTests/bin/Debug/net5.0/Plugins
      - run: cp -r src/Tests/compatibility/netcoreapp3.0/PluginF src/Tests/Prise.IntegrationTests/bin/Debug/net5.0/Plugins
      - run: cp -r src/Tests/compatibility/netstandard2.0/LegacyPlugin1.4 src/Tests/Prise.IntegrationTests/bin/Debug/net5.0/Plugins
      - run: cp -r src/Tests/compatibility/netstandard2.0/LegacyPlugin1.5 src/Tests/Prise.IntegrationTests/bin/Debug/net5.0/Plugins
      
      - run: cp src/Tests/compatibility/netcoreapp3.0/*.nupkg src/Tests/Prise.IntegrationTests/bin/Debug/net5.0/Plugins
      
      - name: Test Prise.IntegrationTests with net5.0
        run: dotnet test src/Tests/Prise.IntegrationTests/Prise.IntegrationTests.csproj