name: Prise unit tests

on: [push]

jobs:
  run-unit-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        
      - name: Setup .NET Core 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100-preview.4.20258.7

      - name: Test Prise.Tests with net5.0
        run: dotnet test src/Tests/Prise.Tests/Prise.Tests.csproj -f net5.0