name: Prise unit tests

env:
  dotnetVersion: 3.1.201
  fwkVersion: 'netcoreapp3.1'

on: [push]

jobs:
  run-unit-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        
      - name: Setup .NET Core ${{dotnetVersion}}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{dotnetVersion}}

      - name: Test Prise.Tests with ${{dotnetVersion}}
        run: dotnet test src/Tests/Prise.Tests/Prise.Tests.csproj -f ${{fwkVersion}}